In [10]:
import pandas as pd
df = pd.read_csv('./data/gapminder.tsv', sep='\t')

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
print(df)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [13]:
display(df)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

200

In [16]:
200
print(100)
#버퍼에 200 지우고 100 넣기때문에 200은 출력 안됨

100

In [17]:
df.shape

(1704, 6)

In [19]:
df.shape[0]

1704

In [23]:
print( f'행 개수는 {df.shape[0]}' )
print( f'열 개수는 {df.shape[1]}' )

행 개수는 1704
열 개수는 6

In [28]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [29]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [92]:
df.dtypes #각 열이 어떤 데이터 타입인지

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [32]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [33]:
df['year']

0       1952
1       1957
2       1962
3       1967
4       1972
        ...
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [37]:
df.year.unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [40]:
df['country'] #시리즈타입, 칼럼이 하나
df.country #약칭, 똑같은 속성,이름 있으면 안됨

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [39]:
df[ ['country'] ] #데이터프레임, 출력에 칼럼명 보임 
#바깥[] 여러개 뽑음, 안쪽[] 칼럼 만듦

          country
0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
...           ...
1699     Zimbabwe
1700     Zimbabwe
1701     Zimbabwe
1702     Zimbabwe
1703     Zimbabwe

[1704 rows x 1 columns]

In [41]:
df[ ['country','year','pop'] ] #출력 순서 바꾸기

          country  year       pop
0     Afghanistan  1952   8425333
1     Afghanistan  1957   9240934
2     Afghanistan  1962  10267083
3     Afghanistan  1967  11537966
4     Afghanistan  1972  13079460
...           ...   ...       ...
1699     Zimbabwe  1987   9216418
1700     Zimbabwe  1992  10704340
1701     Zimbabwe  1997  11404948
1702     Zimbabwe  2002  11926563
1703     Zimbabwe  2007  12311143

[1704 rows x 3 columns]

In [42]:
df.loc[3] #첫 세로줄 칼럼명이 대표값(인덱스), 두번째 세로줄 값

country      Afghanistan
continent           Asia
year                1967
lifeExp            34.02
pop             11537966
gdpPercap     836.197138
Name: 3, dtype: object

In [45]:
df.loc[3]['year']

np.int64(1967)

In [46]:
df.loc[[0,3,5]] ['year'] #데이터프레임/ year의 0,3,5 값

0    1952
3    1967
5    1977
Name: year, dtype: int64

In [47]:
df.loc[[0,3,5]] ['year'][5] #1977

np.int64(1977)

In [48]:
df.iloc[[0,3,5]] ['year'] #지금은 동일한 값 반환
#iloc는 행번호 추출

0    1952
3    1967
5    1977
Name: year, dtype: int64

In [49]:
df.iloc[-1] #순번으로 작동해서 가능

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [55]:
df.loc[[5,0,3]]

       country continent  year  lifeExp       pop   gdpPercap
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
3  Afghanistan      Asia  1967   34.020  11537966  836.197138

In [54]:
df.loc[[5,0,3]].iloc[0] #순번은 무조건 결과의 0,1,2

country      Afghanistan
continent           Asia
year                1977
lifeExp           38.438
pop             14880372
gdpPercap      786.11336
Name: 5, dtype: object

In [93]:
#df.loc[ 행인덱스, 열이름 ]
print(df.loc[ 0, 'year' ]) #프린트하면 값만 나옴

1952

In [59]:
df.loc[[0,2,1700],['country','year','pop']]

          country  year       pop
0     Afghanistan  1952   8425333
2     Afghanistan  1962  10267083
1700     Zimbabwe  1992  10704340

In [60]:
df.loc[:,'year'] #year칼럼의 모든 행
df.loc[1:4,'year'] #year칼럼의 1~4
df.loc[:4,'year'] #year칼럼의 0~4
df.loc[1700:,'year'] #year칼럼의 1700~끝

1700    1992
1701    1997
1702    2002
1703    2007
Name: year, dtype: int64

In [61]:
df.loc[1,:] #1번행 모든 칼럼
df.loc[1,: 'pop'] #1번행 pop열까지
df.loc[1,'year' : 'pop'] #1번행 year열부터 pop열까지
df.loc[1,'year' : ] #1번행 year열부터 마지막까지
df.loc[1:4, 'year' : 'pop'] #1~4행 year열부터 pop까지
df.loc[[4,1,2], 'year' : 'pop'] #4,1,2번행, year열부터 pop열까지

   year  lifeExp       pop
4  1972   36.088  13079460
1  1957   30.332   9240934
2  1962   31.997  10267083

In [78]:
#df.loc[조건식] #조건식을 만족하는 행 추출
b1 = df['year'] < 1960
df.loc[b1] #True인 행만 추출
df.loc[df['year'] <1960 ] #한줄로

          country continent  year  lifeExp      pop    gdpPercap
0     Afghanistan      Asia  1952   28.801  8425333   779.445314
1     Afghanistan      Asia  1957   30.332  9240934   820.853030
12        Albania    Europe  1952   55.230  1282697  1601.056136
13        Albania    Europe  1957   59.280  1476505  1942.284244
24        Algeria    Africa  1952   43.077  9279525  2449.008185
...           ...       ...   ...      ...      ...          ...
1669  Yemen, Rep.      Asia  1957   33.970  5498090   804.830455
1680       Zambia    Africa  1952   42.038  2672000  1147.388831
1681       Zambia    Africa  1957   44.077  3016000  1311.956766
1692     Zimbabwe    Africa  1952   48.451  3080907   406.884115
1693     Zimbabwe    Africa  1957   50.469  3646340   518.764268

[284 rows x 6 columns]

In [82]:
#한국정보찾기
r1 = df['country'].str.contains('Korea, Rep')
sum(r1)
df.loc[r1]
r1 = df['country'] == 'Korea, Rep'

Empty DataFrame
Columns: [country, continent, year, lifeExp, pop, gdpPercap]
Index: []

In [83]:
#기초통계정보(숫자형 칼럼들의)
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [84]:
df['year'].unique() #unique 중복값 없이

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [87]:
#year가 1952인 행들만 추출
y1952 = df.loc[df['year']==1952]['lifeExp'].mean
y1957 = df.loc[df['year']==1957]['lifeExp'].mean
y1952,y1957

(<bound method Series.mean of 0       28.801
 12      55.230
 24      43.077
 36      30.015
 48      62.485
          ...
 1644    40.412
 1656    43.160
 1668    32.548
 1680    42.038
 1692    48.451
 Name: lifeExp, Length: 142, dtype: float64>,
 <bound method Series.mean of 1       30.332
 13      59.280
 25      45.685
 37      31.999
 49      64.399
          ...
 1645    42.887
 1657    45.671
 1669    33.970
 1681    44.077
 1693    50.469
 Name: lifeExp, Length: 142, dtype: float64>)

In [89]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64