In [4]:
import pandas as pd
df = pd.read_csv('./data/gapminder.tsv',sep='\t')

In [7]:
#둘다 같은거
# df['year'].unique() 
df.year.unique() #컬럼이름을 .다음에 쓸 수 있음

df.year.nunique() #유니크 개수

12

# 제목1
## 제목2
### 제목3
#### 제목4
##### 제목5
###### 제목6
### 제목33


1. 제목 (Headers)
문장 앞에 # 개수를 조절하여 제목 크기를 결정합니다. 
# 제목 1 (가장 큼)
## 제목 2
### 제목 3 (점점 작아짐)
2. 텍스트 강조 (Emphasis)
글자의 스타일을 변경할 때 사용합니다. 
위키독스
위키독스
 +1
굵게: **텍스트** 또는 __텍스트__
기울임: *텍스트* 또는 _텍스트_
취소선: ~~텍스트~~ 
3. 목록 (Lists)
순서가 있거나 없는 목록을 만듭니다. 
나무위키
나무위키
 +1
순서 없는 목록: -, *, + 중 하나를 사용 (예: - 항목)
순서 있는 목록: 숫자를 사용 (예: 1. 첫 번째, 2. 두 번째) 
4. 링크 및 이미지 (Links & Images)
외부 주소나 이미지를 연결합니다. 
링크: [표시할 이름](URL 주소)
이미지: ![이미지 설명](이미지 주소) 
5. 인용문 및 코드 (Quotes & Code)
특정 문단을 강조하거나 코드를 삽입할 때 사용합니다. 
인용문: 문장 앞에 > 사용
코드:
인라인 코드: `코드`
코드 블록: 상단과 하단을 ``` (백틱 3개)로 감쌈 
6. 기타 유용한 문법

- 100
-- 100
-- 100

In [15]:
# - 100
# -- 200

# df = pdrw

IndentationError: unexpected indent (1224090610.py, line 4)

In [26]:
# 2가지 방법
# b1 = df['year'] == 1952
# df[b1]
b1 = df.year == 1952
df.loc[b1, :]
#1번째 방법을 한줄을 간단하게!!!!!!!!!!!!!!!!!!!!!!!!!!!1
df.query('year == 1952' )

#2000년 전 이전 한국의 연도별 인구수
# df.query(' country == "Korea, Rep." and year < 2000 ')[['year','pop']]
year = 2000
df.query('country == "Cuba" and year < 2000')

    country continent  year  lifeExp       pop    gdpPercap
384    Cuba  Americas  1952   59.421   6007797  5586.538780
385    Cuba  Americas  1957   62.325   6640752  6092.174359
386    Cuba  Americas  1962   65.246   7254373  5180.755910
387    Cuba  Americas  1967   68.290   8139332  5690.268015
388    Cuba  Americas  1972   70.723   8831348  5305.445256
389    Cuba  Americas  1977   72.649   9537988  6380.494966
390    Cuba  Americas  1982   73.717   9789224  7316.918107
391    Cuba  Americas  1987   74.174  10239839  7532.924763
392    Cuba  Americas  1992   74.414  10723260  5592.843963
393    Cuba  Americas  1997   76.151  10983007  5431.990415

In [27]:
import numpy as np
df.groupby('continent')['lifeExp'].agg(np.mean)

C:\Users\MBC\AppData\Local\Temp\ipykernel_9856\1187918605.py:2: FutureWarning: The provided callable <function mean at 0x0000020211769620> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('continent')['lifeExp'].agg(np.mean)

continent
Africa      48.865330
Americas    64.658737
Asia        60.064903
Europe      71.903686
Oceania     74.326208
Name: lifeExp, dtype: float64

In [31]:
df.groupby('continent').agg(
    최고=('lifeExp','max'),
    평균=('lifeExp','mean')
)

               최고         평균
continent
Africa     76.442  48.865330
Americas   80.653  64.658737
Asia       82.603  60.064903
Europe     81.757  71.903686
Oceania    81.235  74.326208

In [30]:
ebola = pd.read_csv('./data/country_timeseries.csv')
#정상치 개수
print(ebola.count())

Date                   122
Day                    122
Cases_Guinea            93
Cases_Liberia           83
Cases_SierraLeone       87
Cases_Nigeria           38
Cases_Senegal           25
Cases_UnitedStates      18
Cases_Spain             16
Cases_Mali              12
Deaths_Guinea           92
Deaths_Liberia          81
Deaths_SierraLeone      87
Deaths_Nigeria          38
Deaths_Senegal          22
Deaths_UnitedStates     18
Deaths_Spain            16
Deaths_Mali             12
dtype: int64

In [67]:
ebola = pd.read_csv(
    './data/country_timeseries.csv',
    parse_dates=['Date'] #글자를 데이트로 인식
    )
ebola

          Date  Day  Cases_Guinea  Cases_Liberia  ...  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali
0   2015-01-05  289        2776.0            NaN  ...             NaN                  NaN           NaN          NaN
1   2015-01-04  288        2775.0            NaN  ...             NaN                  NaN           NaN          NaN
2   2015-01-03  287        2769.0         8166.0  ...             NaN                  NaN           NaN          NaN
3   2015-01-02  286           NaN         8157.0  ...             NaN                  NaN           NaN          NaN
4   2014-12-31  284        2730.0         8115.0  ...             NaN                  NaN           NaN          NaN
..         ...  ...           ...            ...  ...             ...                  ...           ...          ...
117 2014-03-27    5         103.0            8.0  ...             NaN                  NaN           NaN          NaN
118 2014-03-26    4          86.0            NaN  ...             NaN                  NaN           NaN          NaN
119 2014-03-25    3          86.0            NaN  ...             NaN                  NaN           NaN          NaN
120 2014-03-24    2          86.0            NaN  ...             NaN                  NaN           NaN          NaN
121 2014-03-22    0          49.0            NaN  ...             NaN                  NaN           NaN          NaN

[122 rows x 18 columns]

In [68]:
#결측치 여부
ebola.isnull().sum() #칼럼별 True(결측) 개수

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [69]:
ebola

          Date  Day  Cases_Guinea  Cases_Liberia  ...  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali
0   2015-01-05  289        2776.0            NaN  ...             NaN                  NaN           NaN          NaN
1   2015-01-04  288        2775.0            NaN  ...             NaN                  NaN           NaN          NaN
2   2015-01-03  287        2769.0         8166.0  ...             NaN                  NaN           NaN          NaN
3   2015-01-02  286           NaN         8157.0  ...             NaN                  NaN           NaN          NaN
4   2014-12-31  284        2730.0         8115.0  ...             NaN                  NaN           NaN          NaN
..         ...  ...           ...            ...  ...             ...                  ...           ...          ...
117 2014-03-27    5         103.0            8.0  ...             NaN                  NaN           NaN          NaN
118 2014-03-26    4          86.0            NaN  ...             NaN                  NaN           NaN          NaN
119 2014-03-25    3          86.0            NaN  ...             NaN                  NaN           NaN          NaN
120 2014-03-24    2          86.0            NaN  ...             NaN                  NaN           NaN          NaN
121 2014-03-22    0          49.0            NaN  ...             NaN                  NaN           NaN          NaN

[122 rows x 18 columns]

In [70]:
ebola.fillna(method='ffill').head() #2번꺼로 3번체움

C:\Users\MBC\AppData\Local\Temp\ipykernel_9856\3562105026.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ebola.fillna(method='ffill').head() #2번꺼로 3번체움

        Date  Day  Cases_Guinea  Cases_Liberia  ...  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali
0 2015-01-05  289        2776.0            NaN  ...             NaN                  NaN           NaN          NaN
1 2015-01-04  288        2775.0            NaN  ...             NaN                  NaN           NaN          NaN
2 2015-01-03  287        2769.0         8166.0  ...             NaN                  NaN           NaN          NaN
3 2015-01-02  286        2769.0         8157.0  ...             NaN                  NaN           NaN          NaN
4 2014-12-31  284        2730.0         8115.0  ...             NaN                  NaN           NaN          NaN

[5 rows x 18 columns]

In [71]:
ebola.fillna(method='bfill').head() #뒤에서부터 앞으로 4번꺼로 3번채움

C:\Users\MBC\AppData\Local\Temp\ipykernel_9856\4061156413.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ebola.fillna(method='bfill').head() #뒤에서부터 앞으로 4번꺼로 3번채움

        Date  Day  Cases_Guinea  Cases_Liberia  ...  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali
0 2015-01-05  289        2776.0         8166.0  ...             0.0                  1.0           0.0          6.0
1 2015-01-04  288        2775.0         8166.0  ...             0.0                  1.0           0.0          6.0
2 2015-01-03  287        2769.0         8166.0  ...             0.0                  1.0           0.0          6.0
3 2015-01-02  286        2730.0         8157.0  ...             0.0                  1.0           0.0          6.0
4 2014-12-31  284        2730.0         8115.0  ...             0.0                  1.0           0.0          6.0

[5 rows x 18 columns]

In [72]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [73]:
#타임별 평균팁
tips.groupby('time')['tip'].mean()

C:\Users\MBC\AppData\Local\Temp\ipykernel_9856\2235534799.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('time')['tip'].mean()

time
Lunch     2.728088
Dinner    3.102670
Name: tip, dtype: float64

In [74]:
#성별 타임별 평균팁
tips.groupby(['sex','time'])['tip'].mean()

C:\Users\MBC\AppData\Local\Temp\ipykernel_9856\301251944.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex','time'])['tip'].mean()

sex     time
Male    Lunch     2.882121
        Dinner    3.144839
Female  Lunch     2.582857
        Dinner    3.002115
Name: tip, dtype: float64

In [75]:
from datetime import datetime
t1 = datetime.now()
t2 = datetime(2004,2,21)
diff = t1 - t2
print(diff)
print((type)(diff))

8083 days, 12:45:10.873328
<class 'datetime.timedelta'>

In [76]:
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 122 non-null    datetime64[ns]
 1   Day                  122 non-null    int64
 2   Cases_Guinea         93 non-null     float64
 3   Cases_Liberia        83 non-null     float64
 4   Cases_SierraLeone    87 non-null     float64
 5   Cases_Nigeria        38 non-null     float64
 6   Cases_Senegal        25 non-null     float64
 7   Cases_UnitedStates   18 non-null     float64
 8   Cases_Spain          16 non-null     float64
 9   Cases_Mali           12 non-null     float64
 10  Deaths_Guinea        92 non-null     float64
 11  Deaths_Liberia       81 non-null     float64
 12  Deaths_SierraLeone   87 non-null     float64
 13  Deaths_Nigeria       38 non-null     float64
 14  Deaths_Senegal       22 non-null     float64
 15  Deaths_UnitedStates  18 non-null     float64
 16  Deaths_Spain         16 non-null     float64
 17  Deaths_Mali          12 non-null     float64
dtypes: datetime64[ns](1), float64(16), int64(1)
memory usage: 17.3 KB

In [77]:
ebola.head()

        Date  Day  Cases_Guinea  Cases_Liberia  ...  Deaths_Senegal  Deaths_UnitedStates  Deaths_Spain  Deaths_Mali
0 2015-01-05  289        2776.0            NaN  ...             NaN                  NaN           NaN          NaN
1 2015-01-04  288        2775.0            NaN  ...             NaN                  NaN           NaN          NaN
2 2015-01-03  287        2769.0         8166.0  ...             NaN                  NaN           NaN          NaN
3 2015-01-02  286           NaN         8157.0  ...             NaN                  NaN           NaN          NaN
4 2014-12-31  284        2730.0         8115.0  ...             NaN                  NaN           NaN          NaN

[5 rows x 18 columns]

In [78]:
ebola['date_dt'] = pd.to_datetime(ebola['Date'], format='%m/%d/%Y')
ebola.info()
#date_dt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 122 non-null    datetime64[ns]
 1   Day                  122 non-null    int64
 2   Cases_Guinea         93 non-null     float64
 3   Cases_Liberia        83 non-null     float64
 4   Cases_SierraLeone    87 non-null     float64
 5   Cases_Nigeria        38 non-null     float64
 6   Cases_Senegal        25 non-null     float64
 7   Cases_UnitedStates   18 non-null     float64
 8   Cases_Spain          16 non-null     float64
 9   Cases_Mali           12 non-null     float64
 10  Deaths_Guinea        92 non-null     float64
 11  Deaths_Liberia       81 non-null     float64
 12  Deaths_SierraLeone   87 non-null     float64
 13  Deaths_Nigeria       38 non-null     float64
 14  Deaths_Senegal       22 non-null     float64
 15  Deaths_UnitedStates  18 non-null     float64
 16  Deaths_Spain         16 non-null     float64
 17  Deaths_Mali          12 non-null     float64
 18  date_dt              122 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(16), int64(1)
memory usage: 18.2 KB

In [79]:
ebola['outbreak_d'] = ebola['date_dt'] - ebola['date_dt'].min()
print(ebola[['Date', 'Day', 'outbreak_d']])
#각 행의 날짜 - 최초발병날 = 발병 후 결과일

          Date  Day outbreak_d
0   2015-01-05  289   289 days
1   2015-01-04  288   288 days
2   2015-01-03  287   287 days
3   2015-01-02  286   286 days
4   2014-12-31  284   284 days
..         ...  ...        ...
117 2014-03-27    5     5 days
118 2014-03-26    4     4 days
119 2014-03-25    3     3 days
120 2014-03-24    2     2 days
121 2014-03-22    0     0 days

[122 rows x 3 columns]