In [5]:
import pandas as pd
df1 = pd.read_csv('./data/concat_1.csv')
df2 = pd.read_csv('./data/concat_2.csv')
df3 = pd.read_csv('./data/concat_3.csv')
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [6]:
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [7]:
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [11]:
#행방향 연걸
df4 = pd.concat([df1,df2,df3])
df4
#칼럼 이름이 다르면 버려짐 같은 애들만 남음

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [12]:
df5 = pd.DataFrame(
    data=[["n1", "n2", "n3", "n4"]],
    columns=["A", "B", "C", "D"],
)
print(df5)

    A   B   C   D
0  n1  n2  n3  n4

In [51]:
df4 = pd.concat([df4,df5])
df4

    index    A    B    C    D
0     0.0   a0   b0   c0   d0
1     1.0   a1   b1   c1   d1
2     2.0   a2   b2   c2   d2
3     3.0   a3   b3   c3   d3
4     0.0   a4   b4   c4   d4
5     1.0   a5   b5   c5   d5
6     2.0   a6   b6   c6   d6
7     3.0   a7   b7   c7   d7
8     0.0   a8   b8   c8   d8
9     1.0   a9   b9   c9   d9
10    2.0  a10  b10  c10  d10
11    3.0  a11  b11  c11  d11
0     NaN   n1   n2   n3   n4
0     NaN   n1   n2   n3   n4

In [52]:
df4.loc[0]

   index   A   B   C   D
0    0.0  a0  b0  c0  d0
0    NaN  n1  n2  n3  n4
0    NaN  n1  n2  n3  n4

In [17]:
df4 = df4.reset_index()
df4

    index    A    B    C    D
0       0   a0   b0   c0   d0
1       1   a1   b1   c1   d1
2       2   a2   b2   c2   d2
3       3   a3   b3   c3   d3
4       0   a4   b4   c4   d4
5       1   a5   b5   c5   d5
6       2   a6   b6   c6   d6
7       3   a7   b7   c7   d7
8       0   a8   b8   c8   d8
9       1   a9   b9   c9   d9
10      2  a10  b10  c10  d10
11      3  a11  b11  c11  d11

In [53]:
col_concat = pd.concat([df1, df2, df3], axis="columns", ignore_index=True)
print(col_concat)

    0    1    2    3    4    5    6    7    8    9    10   11
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5  a10  b10  c10  d10
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7  a11  b11  c11  d11

In [54]:
df1.columns = ['A', 'B', 'C', 'D'] #기존에 있는 열 이름만 바꾸는거
df2.columns = ['E', 'F', 'G', 'H']
df3.columns = ['A', 'C', 'F', 'H']
print(df1)
print(df2)
print(df3)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
    E   F   G   H
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7
     A    C    F    H
0   a8   b8   c8   d8
2   a9   b9   c9   d9
5  a10  b10  c10  d10
7  a11  b11  c11  d11

In [22]:
row_concat = pd.concat([df1, df2, df3])
print(row_concat)

     A    B    C    D    E    F    G    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   a4   b4   c4   d4
1  NaN  NaN  NaN  NaN   a5   b5   c5   d5
2  NaN  NaN  NaN  NaN   a6   b6   c6   d6
3  NaN  NaN  NaN  NaN   a7   b7   c7   d7
0   a8  NaN   b8  NaN  NaN   c8  NaN   d8
1   a9  NaN   b9  NaN  NaN   c9  NaN   d9
2  a10  NaN  b10  NaN  NaN  c10  NaN  d10
3  a11  NaN  b11  NaN  NaN  c11  NaN  d11

In [24]:
#공통부분만 남김
row_concat = pd.concat([df1, df3],join='inner')
print(row_concat)

     A    C
0   a0   c0
1   a1   c1
2   a2   c2
3   a3   c3
0   a8   b8
1   a9   b9
2  a10  b10
3  a11  b11

In [26]:
df1.index = [0, 1, 2, 3]
df2.index = [4, 5, 6, 7]
df3.index = [0, 2, 5, 7]
print(df1)
print(df2)
print(df3)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
    E   F   G   H
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7
     A    C    F    H
0   a8   b8   c8   d8
2   a9   b9   c9   d9
5  a10  b10  c10  d10
7  a11  b11  c11  d11

In [40]:
col_concat = pd.concat([df1,df2, df3], axis="columns",join='outer')
print(col_concat)

     A    B    C    D    E    F    G    H    A    C    F    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5  a10  b10  c10  d10
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7  a11  b11  c11  d11

In [39]:
col_concat = pd.concat([df1, df3], axis="columns",join='outer')
print(col_concat)

     A    B    C    D    A    C    F    H
0   a0   b0   c0   d0   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  a10  b10  c10  d10
7  NaN  NaN  NaN  NaN  a11  b11  c11  d11

In [34]:
col_concat = pd.concat([df1, df3], axis="columns",join='inner')
print(col_concat)
#join='inner' 공통 부분만

    A   B   C   D   A   C   F   H
0  a0  b0  c0  d0  a8  b8  c8  d8
2  a2  b2  c2  d2  a9  b9  c9  d9

In [43]:
person = pd.read_csv('./data/survey_person.csv')
site = pd.read_csv('./data/survey_site.csv')
survey = pd.read_csv('./data/survey_survey.csv')
visited = pd.read_csv('./data/survey_visited.csv')
print(person)
print(survey)

      ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth
    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [44]:
visited_subset = visited.loc[[0, 2, 6], :]
print(visited_subset)

   ident   site       dated
0    619   DR-1  1927-02-08
2    734   DR-3  1939-01-07
6    837  MSK-4  1932-01-14

In [45]:
#인덱스말고 값으로 연결
o2o_merge = site.merge(visited_subset, left_on="name", right_on="site")
print(o2o_merge)

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [46]:
#6이 빠지면
visited_subset = visited.loc[[0, 2,], :]
print(visited_subset)

   ident  site       dated
0    619  DR-1  1927-02-08
2    734  DR-3  1939-01-07

In [49]:
o2o_merge = site.merge(visited_subset, left_on="name", right_on="site", how='left')
print(o2o_merge)

    name    lat    long  ident  site       dated
0   DR-1 -49.85 -128.57  619.0  DR-1  1927-02-08
1   DR-3 -47.15 -126.72  734.0  DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    NaN   NaN         NaN