In [4]:
import pandas as pd
# 2번째 행(인덱스 1)을 제외하고 로드
df = pd.read_csv('data/주유소_데이터.csv', skiprows=[1],thousands=',', encoding='cp949')

In [5]:
df

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260306,SK에너지,셀프,2217,1997,1875,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260307,SK에너지,셀프,2217,1997,1995,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260308,SK에너지,셀프,2217,1997,1995,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260309,SK에너지,셀프,2287,1997,1995,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260310,SK에너지,셀프,2287,1997,1995,0
...,...,...,...,...,...,...,...,...,...,...,...
12622,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20260401,GS칼텍스,셀프,2120,1949,1919,0
12623,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20260402,GS칼텍스,셀프,2227,1949,1919,0
12624,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20260403,GS칼텍스,셀프,2227,1993,1978,0
12625,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20260404,GS칼텍스,셀프,2227,1993,1978,0
12626,A0009138,서울 중랑구,우림주유소,서울 중랑구 용마산로 487 (망우제3동),20260405,GS칼텍스,셀프,2227,1993,1978,0

In [7]:
d= df[['지역','기간','휘발유']]
d

           지역        기간   휘발유
0      서울 강남구  20260306  1997
1      서울 강남구  20260307  1997
2      서울 강남구  20260308  1997
3      서울 강남구  20260309  1997
4      서울 강남구  20260310  1997
...       ...       ...   ...
12622  서울 중랑구  20260401  1949
12623  서울 중랑구  20260402  1949
12624  서울 중랑구  20260403  1993
12625  서울 중랑구  20260404  1993
12626  서울 중랑구  20260405  1993

[12627 rows x 3 columns]

In [8]:
df.상표.unique() #유니크는 중복없앰

array(['SK에너지', 'S-OIL', 'GS칼텍스', 'HD현대오일뱅크', '알뜰주유소', '알뜰(ex)', '자가상표'],
      dtype=object)

In [9]:
df.shape

(12627, 11)

In [10]:
d.loc[1000, '휘발유']

np.int64(1839)

In [15]:
df.loc[1:5,'기간']

1    20260307
2    20260308
3    20260309
4    20260310
5    20260311
Name: 기간, dtype: int64

In [27]:
r = df['휘발유'] > 2000
df.loc[r,['지역','기간','휘발유']] #열 리스트를 따로 묶기

           지역        기간   휘발유
24     서울 강남구  20260330  2065
25     서울 강남구  20260331  2065
26     서울 강남구  20260401  2065
27     서울 강남구  20260402  2065
28     서울 강남구  20260403  2065
...       ...       ...   ...
12249  서울 중랑구  20260331  2019
12250  서울 중랑구  20260401  2019
12251  서울 중랑구  20260402  2019
12470  서울 중랑구  20260404  2058
12471  서울 중랑구  20260405  2058

[1256 rows x 3 columns]

In [37]:
a = df['상표'].str.contains('SK') #포함
sum(a) #True의 개수 True=1, False=0
a.sum()

np.int64(3582)

In [33]:
df.loc[a]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260306,SK에너지,셀프,2217,1997,1875,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260307,SK에너지,셀프,2217,1997,1995,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260308,SK에너지,셀프,2217,1997,1995,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260309,SK에너지,셀프,2287,1997,1995,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260310,SK에너지,셀프,2287,1997,1995,0
...,...,...,...,...,...,...,...,...,...,...,...
12591,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260401,SK에너지,셀프,0,1998,1978,1600
12592,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260402,SK에너지,셀프,0,1998,1978,1600
12593,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260403,SK에너지,셀프,0,1998,1978,1700
12594,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260404,SK에너지,셀프,0,1998,1978,1700
12595,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260405,SK에너지,셀프,0,1998,1978,1700

In [38]:
r1 = df['상표'] == "SK에너지" #특정
df.loc[ r1 ]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260306,SK에너지,셀프,2217,1997,1875,0
1,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260307,SK에너지,셀프,2217,1997,1995,0
2,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260308,SK에너지,셀프,2217,1997,1995,0
3,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260309,SK에너지,셀프,2287,1997,1995,0
4,A0006039,서울 강남구,(유)동하석유 힐탑셀프주유소,서울 강남구 논현로 640,20260310,SK에너지,셀프,2287,1997,1995,0
...,...,...,...,...,...,...,...,...,...,...,...
12591,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260401,SK에너지,셀프,0,1998,1978,1600
12592,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260402,SK에너지,셀프,0,1998,1978,1600
12593,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260403,SK에너지,셀프,0,1998,1978,1700
12594,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260404,SK에너지,셀프,0,1998,1978,1700
12595,A0010081,서울 중랑구,용마로주유소,서울 중랑구 용마산로 309 (면목동),20260405,SK에너지,셀프,0,1998,1978,1700

In [39]:
# 기초통계정보(숫자형 칼럼들의)
df.describe()

                 기간        고급휘발유           휘발유            경유          실내등유
count  1.262700e+04  12627.00000  12627.000000  12627.000000  12627.000000
mean   2.026033e+07   1364.38093   1901.576701   1893.754178    406.955571
std    3.179769e+01   1063.10267    123.651669    118.092024    724.822572
min    2.026031e+07      0.00000      0.000000      0.000000      0.000000
25%    2.026031e+07      0.00000   1810.000000   1799.000000      0.000000
50%    2.026032e+07   2035.00000   1872.000000   1862.000000      0.000000
75%    2.026033e+07   2190.00000   1958.000000   1975.000000      0.000000
max    2.026040e+07   2996.00000   2598.000000   2658.000000   2469.000000